name: 'Resume Template'
author: Rennan Cockles <r3ck.dev@gmail.com>
description: 'Creates a resume and hosts with github pages'
inputs:
  resume_file:
    description: 'Json file with resume data.'
    required: true
  cname:
    description: 'Domain name to use with github pages.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'file-text'
  color: 'purple'
