name: Deploy

on: [push]

jobs:
  resume-action:
    runs-on: ubuntu-latest
    name: Resume Action Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resume Action Step
        id: resume-step
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          resume_file: 'data/pt.json'
